# Start SimpleCov for test coverage reports
require 'simplecov'
require 'simplecov-console'

SimpleCov.start 'rails' do
  add_filter '/bin/'
  add_filter '/db/'
  add_filter '/spec/'      # for rspec
  add_filter '/test/'      # for minitest
  add_filter '/features/'  # for cucumber
end

SimpleCov.formatter = SimpleCov::Formatter::MultiFormatter.new([
  SimpleCov::Formatter::HTMLFormatter,
  SimpleCov::Formatter::Console
])

# This file was generated by the `rails generate rspec:install` command.
# Conventionally, all specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The `.rspec` file contains `--require spec_helper`, so this file is always loaded.
# Keep it light and move heavy dependencies to separate helper files.

RSpec.configure do |config|
  # RSpec expectations configuration
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # RSpec mocks configuration
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # Ensure shared context metadata applies to host groups
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # ---- Recommended settings from both branches ----
  config.filter_run_when_matching :focus
  config.example_status_persistence_file_path = "spec/examples.txt"
  config.disable_monkey_patching!

  # Use the documentation formatter when running a single file
  config.default_formatter = "doc" if config.files_to_run.one?

  # Profile slow examples
  config.profile_examples = 10

  # Run specs in random order to surface order dependencies
  config.order = :random
  Kernel.srand config.seed
end
