name: CI - Ruby on Rails

on:
  push:
    branches: [ main ]
    paths:
      - '**.rb'
      - 'Gemfile'
      - 'Gemfile.lock'
  pull_request:
    branches: [ main ]
    paths:
      - '**.rb'
      - 'Gemfile'
      - 'Gemfile.lock'

jobs:
  # -------------------------
  # 1. Ruby Security Scan (Brakeman)
  # -------------------------
  scan_ruby:
    name: Ruby Security Scan (Brakeman)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Brakeman
        run: gem install brakeman

      - name: Run Brakeman scan
        run: brakeman -A -q --no-progress --format html -o brakeman-report.html

      - name: Upload Brakeman report
        uses: actions/upload-artifact@v4
        with:
          name: brakeman-report
          path: brakeman-report.html

  # -------------------------
  # 2. Ruby Linting (Rubocop)
  # -------------------------
  lint:
    name: Ruby Linting (Rubocop)
    runs-on: ubuntu-latest
    needs: scan_ruby

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install Rubocop
        run: gem install rubocop rubocop-github

      - name: Run Rubocop with GitHub formatter
        run: rubocop --format github

  # -------------------------
  # 3. RSpec Tests
  # -------------------------
  rspec:
    name: Run RSpec Tests
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      RAILS_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Prepare database
        run: |
          echo "Preparing test database (SQLite)..."
          bin/rails db:prepare

      - name: Run RSpec (skip gracefully if none found)
        run: |
          if [ -d "spec" ] && [ "$(find spec -type f -name '*_spec.rb' | wc -l)" -gt 0 ]; then
            echo "Running RSpec tests..."
            bundle exec rspec --format documentation
          else
            echo "No RSpec tests found. Skipping."
          fi

  # -------------------------
  # 4. Cucumber Tests
  # -------------------------
  cucumber:
    name: Run Cucumber Tests
    runs-on: ubuntu-latest
    needs: [rspec]
    env:
      RAILS_ENV: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Prepare database
        run: |
          echo "Preparing test database (SQLite)..."
          bin/rails db:prepare

      - name: Run Cucumber (skip gracefully if none found)
        run: |
          if [ -d "features" ] && [ "$(find features -type f -name '*.feature' | wc -l)" -gt 0 ]; then
            echo "Running Cucumber tests..."
            bundle exec cucumber
          else
            echo "No Cucumber features found. Skipping."
          fi
